#!/usr/bin/env bash

if [[ -z "$GAME" ]]; then
    echo "Must provide GAME in environment" 1>&2
    exit 1
fi

export NODE_ENV=development
#export NODE_OPTIONS="--trace-warnings"

cd server

# this can fail and thats okay
rabbitmqadmin delete queue name='session-actions-1-queue'
rabbitmqadmin delete exchange name='session-actions'
rabbitmqadmin delete exchange name='session-events'
rabbitmqadmin delete exchange name='session-events-1'
./node_modules/.bin/sequelize db:drop

# now we need to start doing things that can't fail
set -e
./node_modules/.bin/sequelize db:create
./node_modules/.bin/sequelize db:migrate


yarn --cwd server run start:dev
