#!/usr/bin/env bash

if [[ -z "$GAME" ]]; then
    echo "Must provide GAME in environment" 1>&2
    exit 1
fi

export NODE_ENV=development
export NODE_OPTIONS="--trace-warnings"

cd server

# this can fail and thats okay
./node_modules/.bin/sequelize db:drop
set -e
./node_modules/.bin/sequelize db:create
./node_modules/.bin/sequelize db:migrate

yarn --cwd server run start:dev
