#!/usr/bin/env bash

set -e

yarn --cwd server install
yarn --cwd game-core/client install
yarn --cwd game-core/server install

# games
yarn --cwd isaac-four-souls/client install
yarn --cwd isaac-four-souls/server install
