#!/usr/bin/env bash

set -e

build_type() {
	local game=$1
	local build_type=$2
	local ext=$3
	rm -rf "${game}/${build_type}/build"
	NODE_ENV=production ./node_modules/.bin/webpack -c "${game}/${build_type}/webpack.config.${ext}"
	dir="$game/$build_type/build"
	digest=$(find "$dir" -type f -exec shasum -a256 {} \; | sed "s~$dir~~g" | LC_ALL=C sort -d | shasum -a256 | awk '{ print $1 }')
	mkdir -p $game/dist/$build_type/$digest
	cp -r "$game/$build_type/build/"* "$game/dist/$build_type/$digest"
}

build() {
	local game=$1
	local publish_mode=$2

	if [[ -z "$publish_mode" ]]; then
	    echo "Usage: scripts/publish [game] [release|beta]" 1>&2
	    exit 1
	fi

	local beta="true"

	if [ "$publish_mode" = "release" ]; then
	    beta="false"
	fi

	echo "Building ${game}..."
	rm -rf "${game}/dist"
	build_type $game "client" "cjs"
	build_type $game "server" "js"

	echo "Uploading ${game}..."
	aws s3 sync --size-only "${game}/dist" "s3://${S3_GAME_BUCKET}/${game}"
	client_digest=$(ls -1 "${game}/dist/client")
	server_digest=$(ls -1 "${game}/dist/server")

	echo "Publishing ${game}..."
	body="{\"serverDigest\":\"${server_digest}\",\"clientDigest\":\"${client_digest}\",\"name\":\"${game}\",\"beta\":${beta}}"
	curl -vvv -g -X PUT -d ${body} -H'Content-Type: application/json' -H "x-publish-token: ${PUBLISH_TOKEN}" https://boardzilla.io/publish

	echo "Done with ${game}"
}

if [[ -z "$PUBLISH_TOKEN" ]]; then
    echo "Must provide PUBLISH_TOKEN in environment" 1>&2
    exit 1
fi

if [[ -z "$S3_GAME_BUCKET" ]]; then
    echo "Must provide S3_GAME_BUCKET in environment" 1>&2
    exit 1
fi

game=$1
publish_mode=$2

if [[ -z "$game" ]]; then
    echo "Usage: scripts/publish [game] [release|beta]" 1>&2
    echo "" 1>&2
    echo "No game specified!" 1>&2
    exit 1
fi

if [[ -z "$publish_mode" ]]; then
    echo "Usage: scripts/publish [game] [release|beta]" 1>&2
    echo "" 1>&2
    echo "No publish_mode specified!" 1>&2
    exit 1
fi

aws s3 sync --size-only assets "s3://${S3_GAME_BUCKET}/assets"
build $game $publish_mode
