#!/usr/bin/env bash

set -e

build_type() {
	local game=$1
	local build_type=$2
	local ext=$3
	rm -rf "${game}/${build_type}/build"
	./node_modules/.bin/webpack -c "${game}/${build_type}/webpack.config.${ext}"
	dir="$game/$build_type/build"
	digest=$(find "$dir" -type f -exec shasum -a256 {} \; | sed "s~$dir~~g" | LC_ALL=C sort -d | shasum -a256 | awk '{ print $1 }')
	mkdir -p $game/dist/$build_type/$digest
	cp -r "$game/$build_type/build/"* "$game/dist/$build_type/$digest"
}

build() {
	local game=$1
	echo "Building ${game}..."
	rm -rf "${game}/dist"
	build_type $game "client" "cjs"
	build_type $game "server" "js"

	echo "Uploading ${game}..."
	aws s3 sync --size-only "${game}/dist" "s3://${S3_GAME_BUCKET}/${game}"
	client_digest=$(ls -1 "${game}/dist/client")
	server_digest=$(ls -1 "${game}/dist/server")

	echo "Publishing ${game}..."
	body="{\"serverDigest\":\"${server_digest}\",\"clientDigest\":\"${client_digest}\",\"name\":\"${game}\"}"
	curl -vvv -g -X PUT -d ${body} -H'Content-Type: application/json' -H "x-publish-token: ${PUBLISH_TOKEN}" https://boardzilla.io/publish

	echo "Done with ${game}"
}

if [[ -z "$PUBLISH_TOKEN" ]]; then
    echo "Must provide PUBLISH_TOKEN in environment" 1>&2
    exit 1
fi

if [[ -z "$S3_GAME_BUCKET" ]]; then
    echo "Must provide S3_GAME_BUCKET in environment" 1>&2
    exit 1
fi

for game in $(cat GAMES); do
	build $game
done
